
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flixsa_api
    username: root
    password: test env password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
      continue-on-error: false

#logging:
#  level:
#    root: INFO
#    org:
#      springframework: ERROR
#      hibernate: ERROR
secrets:
  randomkey: 9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9
